
    CREATE TABLE ZONE (
        ZONEID INT PRIMARY KEY,
        ZONENAME VARCHAR2(20)
    );

    INSERT ALL
    INTO ZONE (ZONEID, ZONENAME) VALUES (1, 'ATHWA')
    INTO ZONE (ZONEID, ZONENAME) VALUES (2, 'VARCHA')
    INTO ZONE (ZONEID, ZONENAME) VALUES (3, 'NANPURA')
    INTO ZONE (ZONEID, ZONENAME) VALUES (4, 'VESU')
    INTO ZONE (ZONEID, ZONENAME) VALUES (5, 'DINDOLI')
    INTO ZONE (ZONEID, ZONENAME) VALUES (6, 'DUMAS')
    INTO ZONE (ZONEID, ZONENAME) VALUES (7, 'RANDER')
    INTO ZONE (ZONEID, ZONENAME) VALUES (8, 'PAL')
    SELECT * FROM dual;

    CREATE TABLE WARD (
        WARDID INT PRIMARY KEY,
        ZONEID INT NOT NULL,
        WARDNAME VARCHAR2(20),
        FOREIGN KEY (ZONEID) REFERENCES ZONE(ZONEID)
    );

    INSERT ALL
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (1, 1, 'GHOD DOD')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (2, 1, 'BHATAR')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (3, 2, 'MOTA VARCHA')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (4, 2, 'SARTHNA')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (5, 3, 'TIMALAYAWADI')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (6, 3, 'NANPUR LIBRARY')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (7, 4, 'VIP ROAD')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (8, 4, 'VESU GAM')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (9, 5, 'DINDOLI WEST')
    INTO WARD (WARDID, ZONEID, WARDNAME) VALUES (10, 5, 'DINDOLI EAST')
    SELECT * FROM dual;

    CREATE TABLE PATIENTCATEGORYMASTER (
        CATEGORYID INT PRIMARY KEY,
        CATEGORYNAME VARCHAR2(20)
    );

    INSERT ALL
    INTO PATIENTCATEGORYMASTER (CATEGORYID, CATEGORYNAME) VALUES (1, 'MILD')
    INTO PATIENTCATEGORYMASTER (CATEGORYID, CATEGORYNAME) VALUES (2, 'MODERATE')
    INTO PATIENTCATEGORYMASTER (CATEGORYID, CATEGORYNAME) VALUES (3, 'CRITICAL')
    INTO PATIENTCATEGORYMASTER (CATEGORYID, CATEGORYNAME) VALUES (4, 'CRITICAL ON VENTILATOR')
    SELECT * FROM dual;

    CREATE TABLE PATIENTMASTER (
        PATIENTID INT PRIMARY KEY,
        PATIENTNAME VARCHAR2(20),
        CATEGORYID INT NOT NULL,
        WARDID INT,
        ADMITTEDDATE DATE,
        DISCHARGEDDATE DATE,
        FOREIGN KEY (CATEGORYID) REFERENCES PATIENTCATEGORYMASTER(CATEGORYID),
        FOREIGN KEY (WARDID) REFERENCES WARD(WARDID)
    );

    INSERT ALL
    INTO PATIENTMASTER VALUES (1, 'RAHUL', 1, 1, '10-JUN-2025', '20-JUN-2025')
    INTO PATIENTMASTER VALUES (2, 'AMIT', 2, 2, '25-JUL-2025', NULL)
    INTO PATIENTMASTER VALUES (3, 'VIKAS', 3, 3, '01-JUN-2025', '18-JUN-2025')
    INTO PATIENTMASTER VALUES (4, 'SANJAY', 4, 4, '28-JUL-2025', NULL)
    INTO PATIENTMASTER VALUES (5, 'RAJESH', 2, 5, '30-MAY-2025', '15-JUN-2025')
    INTO PATIENTMASTER VALUES (6, 'KIRAN', 1, 6, '29-JUL-2025', NULL)
    INTO PATIENTMASTER VALUES (7, 'SURESH', 3, 7, '10-MAY-2025', '20-MAY-2025')
    INTO PATIENTMASTER VALUES (8, 'MANISH', 4, 8, '05-AUG-2025', NULL)
    INTO PATIENTMASTER VALUES (9, 'ARUN', 2, 9, '18-MAY-2025', '02-JUN-2025')
    INTO PATIENTMASTER VALUES (10, 'VIJAY', 1, 10, '06-AUG-2025', NULL)
    INTO PATIENTMASTER VALUES (11, 'RAMESH', 1, 1, '25-JUL-2025', '02-AUG-2025')
    INTO PATIENTMASTER VALUES (12, 'AJAY', 2, 2, '30-JUL-2025', NULL)
    INTO PATIENTMASTER VALUES (13, 'PANKAJ', 3, 3, '01-AUG-2025', '08-AUG-2025')
    INTO PATIENTMASTER VALUES (14, 'SUNIL', 4, 4, '21-JUL-2025', NULL)
    INTO PATIENTMASTER VALUES (15, 'DEEPAK', 2, 5, '03-AUG-2025', NULL)
    INTO PATIENTMASTER VALUES (16, 'ASHOK', 1, 6, '22-JUL-2025', '05-AUG-2025')
    INTO PATIENTMASTER VALUES (17, 'PRAVEEN', 3, 7, '27-JUL-2025', NULL)
    INTO PATIENTMASTER VALUES (18, 'JITENDRA', 4, 8, '05-AUG-2025', NULL)
    INTO PATIENTMASTER VALUES (19, 'NITESH', 1, 9, '08-AUG-2025', '10-AUG-2025')
    INTO PATIENTMASTER VALUES (20, 'ANIL', 2, 10, '09-AUG-2025', NULL)
    INTO PATIENTMASTER VALUES (21, 'HARISH', 3, 1, '06-AUG-2025', NULL)
    INTO PATIENTMASTER VALUES (22, 'LOKESH', 4, 2, '09-AUG-2025', NULL)
    SELECT * FROM dual;
