-- 1.   Create cursor to delete student data whose grade is 'F' from STUDRESULT and insert that record in into another table FAILEDSTUDENTS

Ans.

    DECLARE
        VSTUDREC STUDRESULT%ROWTYPE;
        CURSOR C1 IS 
            SELECT * FROM STUDRESULT
            WHERE GRADE = 'F';

    BEGIN
        OPEN C1;

        LOOP
            FETCH C1 INTO VSTUDREC;
            EXIT WHEN C1%NOTFOUND;

            INSERT INTO FAILEDSTUDENTS VALUES(VSTUDREC.ROLLNO,VSTUDREC.NAME,VSTUDREC.DIV,VSTUDREC.COURSEID,VSTUDREC.SUB1MARKS,VSTUDREC.SUB2MARKS,VSTUDREC.SUB3MARKS,VSTUDREC.SUB4MARKS,VSTUDREC.PER,VSTUDREC.GRADE);
        END LOOP;

        CLOSE C1;

        DELETE FROM STUDRESULT
        WHERE GRADE = 'F';
        
    END;

-- Alternative

    DECLARE
        CURSOR C1 IS 
            SELECT * FROM STUDRESULT
            WHERE GRADE = 'F';

    BEGIN
        FOR VSTUDREC IN C1

        LOOP
            INSERT INTO FAILEDSTUDENTS VALUES(VSTUDREC.ROLLNO,VSTUDREC.NAME,VSTUDREC.DIV,VSTUDREC.COURSEID,VSTUDREC.SUB1MARKS,VSTUDREC.SUB2MARKS,VSTUDREC.SUB3MARKS,VSTUDREC.SUB4MARKS,VSTUDREC.PER,VSTUDREC.GRADE);
        END LOOP;

        DELETE FROM STUDRESULT
        WHERE GRADE = 'F';
        
    END;


-- 2.   Create trigger to generate summary records(Insert data into RESULTSUMMARY table) coursename and grade wise

    DECLARE
        CURSOR C1 IS
            SELECT 
                S.GRADE AS GRADE,
                COUNT(*) AS GRADECOUNT,
                C.COURSENAME AS COURSENAME
            FROM STUDRESULT S
            INNER JOIN COURSE C ON S.COURSEID = C.COURSEID
            GROUP BY S.GRADE, C.COURSENAME;
    BEGIN
        FOR VSTUDREC IN C1 LOOP
            INSERT INTO RESULTSUMMARY VALUES (resultSummarySeq.NEXTVAL, VSTUDREC.GRADE, VSTUDREC.GRADECOUNT, VSTUDREC.COURSENAME);
        END LOOP;
    END;

