-- Creation of STUDRESULT

CREATE TABLE STUDRESULT (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR2(25),
    DIV VARCHAR2(25),
    COURSEID INT,
    SUB1MARKS INT NOT NULL,
    SUB2MARKS INT NOT NULL,
    SUB3MARKS INT NOT NULL,
    SUB4MARKS INT NOT NULL,
    PER NUMBER(5,2),
    GRADE VARCHAR2(10),
    FOREIGN KEY(COURSEID) REFERENCES COURSE(COURSEID)
);

-- Insretion of STUDRESULT

INSERT ALL
    INTO STUDRESULT VALUES (1, 'Amit Shah', 'A', 1, 85, 88, 90, 87, NULL, NULL)
    INTO STUDRESULT VALUES (2, 'Sneha Patel', 'B', 2, 78, 80, 76, 79, NULL, NULL)
    INTO STUDRESULT VALUES (3, 'Karan Mehta', 'C', 3, 60, 65, 62, 64, NULL, NULL)
    INTO STUDRESULT VALUES (4, 'Priya Sharma', 'A', 1, 92, 95, 90, 93, NULL, NULL)
    INTO STUDRESULT VALUES (5, 'Ravi Joshi', 'B', 2, 33, 35, 37, 39, NULL, NULL)
    INTO STUDRESULT VALUES (6, 'Divya Nair', 'C', 3, 55, 58, 54, 57, NULL, NULL)
    INTO STUDRESULT VALUES (7, 'Vikas Rao', 'A', 4, 77, 79, 75, 78, NULL, NULL)
    INTO STUDRESULT VALUES (8, 'Reena Shah', 'B', 5, 81, 84, 86, 83, NULL, NULL)
    INTO STUDRESULT VALUES (9, 'Hardik Dave', 'C', 6, 44, 46, 48, 45, NULL, NULL)
    INTO STUDRESULT VALUES (10, 'Pooja Thakkar', 'A', 1, 69, 70, 72, 68, NULL, NULL)
    INTO STUDRESULT VALUES (11, 'Raj Patel', 'B', 2, 91, 89, 92, 90, NULL, NULL)
    INTO STUDRESULT VALUES (12, 'Nidhi Rao', 'C', 3, 49, 50, 52, 51, NULL, NULL)
    INTO STUDRESULT VALUES (13, 'Harsh Shah', 'A', 4, 61, 63, 64, 62, NULL, NULL)
    INTO STUDRESULT VALUES (14, 'Isha Jain', 'B', 5, 73, 75, 78, 74, NULL, NULL)
    INTO STUDRESULT VALUES (15, 'Mitesh Desai', 'C', 6, 86, 84, 85, 87, NULL, NULL)
    INTO STUDRESULT VALUES (16, 'Sonali Rana', 'A', 1, 38, 35, 40, 37, NULL, NULL)
    INTO STUDRESULT VALUES (17, 'Krupa Mehta', 'B', 2, 59, 58, 57, 56, NULL, NULL)
    INTO STUDRESULT VALUES (18, 'Arjun Kumar', 'C', 3, 82, 84, 83, 81, NULL, NULL)
    INTO STUDRESULT VALUES (19, 'Heena Modi', 'A', 4, 68, 66, 67, 65, NULL, NULL)
    INTO STUDRESULT VALUES (20, 'Deepak Shah', 'B', 5, 90, 92, 91, 93, NULL, NULL)
    INTO STUDRESULT VALUES (21, 'Chirag Shah', 'C', 6, 43, 45, 42, 40, NULL, NULL)
    INTO STUDRESULT VALUES (22, 'Snehal Rathod', 'A', 1, 52, 54, 55, 53, NULL, NULL)
    INTO STUDRESULT VALUES (23, 'Parth Solanki', 'B', 2, 76, 77, 79, 78, NULL, NULL)
    INTO STUDRESULT VALUES (24, 'Komal Chauhan', 'C', 3, 94, 95, 96, 93, NULL, NULL)
    INTO STUDRESULT VALUES (25, 'Ankit Patel', 'A', 4, 62, 60, 63, 61, NULL, NULL)
    INTO STUDRESULT VALUES (26, 'Neha Sharma', 'B', 5, 47, 49, 48, 46, NULL, NULL)
    INTO STUDRESULT VALUES (27, 'Tushar Shah', 'C', 6, 31, 30, 33, 32, NULL, NULL)
    INTO STUDRESULT VALUES (28, 'Ila Joshi', 'A', 1, 85, 87, 88, 89, NULL, NULL)
    INTO STUDRESULT VALUES (29, 'Ramesh Nair', 'B', 2, 69, 70, 71, 68, NULL, NULL)
    INTO STUDRESULT VALUES (30, 'Payal Modi', 'C', 3, 40, 41, 39, 38, NULL, NULL)
    INTO STUDRESULT VALUES (31, 'Kishan Bhatt', 'A', 4, 53, 55, 56, 54, NULL, NULL)
    INTO STUDRESULT VALUES (32, 'Jinal Patel', 'B', 5, 80, 82, 81, 79, NULL, NULL)
    INTO STUDRESULT VALUES (33, 'Hiren Vora', 'C', 6, 66, 67, 65, 64, NULL, NULL)
    INTO STUDRESULT VALUES (34, 'Bhumi Desai', 'A', 1, 92, 91, 94, 93, NULL, NULL)
    INTO STUDRESULT VALUES (35, 'Pratik Gami', 'B', 2, 70, 68, 71, 69, NULL, NULL)
    INTO STUDRESULT VALUES (36, 'Kinjal Shah', 'C', 3, 58, 56, 59, 60, NULL, NULL)
    INTO STUDRESULT VALUES (37, 'Yash Dave', 'A', 4, 45, 47, 44, 46, NULL, NULL)
    INTO STUDRESULT VALUES (38, 'Mehul Bhatt', 'B', 5, 61, 62, 60, 63, NULL, NULL)
    INTO STUDRESULT VALUES (39, 'Twinkle Parmar', 'C', 6, 83, 85, 84, 82, NULL, NULL)
    INTO STUDRESULT VALUES (40, 'Ritika Shah', 'A', 1, 34, 36, 38, 37, NULL, NULL)
SELECT * FROM DUAL;


-- Creation of COURSE

CREATE TABLE COURSE (
    COURSEID INT PRIMARY KEY,
    COURSENAME VARCHAR2(20)
);

-- Insertion

INSERT ALL
    INTO COURSE VALUES (1, 'BSCIT')
    INTO COURSE VALUES (2, 'BBA')
    INTO COURSE VALUES (3, 'BCA')
    INTO COURSE VALUES (4, 'BCom')
    INTO COURSE VALUES (5, 'BA')
    INTO COURSE VALUES (6, 'MBA')
SELECT * FROM DUAL;

-- Creation of DELETEDSTUD

CREATE TABLE DELETEDSTUD (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR2(25),
    DIV VARCHAR2(25),
    COURSEID INT,
    SUB1MARKS INT NOT NULL,
    SUB2MARKS INT NOT NULL,
    SUB3MARKS INT NOT NULL,
    SUB4MARKS INT NOT NULL,
    PER NUMBER(5,2),
    GRADE VARCHAR2(10)
);

-- Creation of FAILEDSTUDENTS

CREATE TABLE FAILEDSTUDENTS (
    ROLLNO INT PRIMARY KEY,
    NAME VARCHAR2(25),
    DIV VARCHAR2(25),
    COURSEID INT,
    SUB1MARKS INT NOT NULL,
    SUB2MARKS INT NOT NULL,
    SUB3MARKS INT NOT NULL,
    SUB4MARKS INT NOT NULL,
    PER NUMBER(5,2),
    GRADE VARCHAR2(10)
);

-- Creation of RESULTSUMMARY

CREATE TABLE RESULTSUMMARY (
    RSID INT PRIMARY KEY,
    GRADE VARCHAR2(10),
    GRADECOUNT INT,
    COURSENAME VARCHAR2(25)
);